---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-newapp
  namespace: argo-events
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    argo-newapp:
      owner: gsfd2000
      repository: argo-newapp
      webhook:
        endpoint: /argo-newapp
        port: "12000"
        method: POST
        url: http://webhook-newapp.172.20.0.2.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-newapp
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: github-newapp-eventsource-svc
           port:
             number: 12000
    host: webhook-newapp.172.20.0.2.nip.io
