apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-workflows
  namespace: workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eventworkflows
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo-events

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eventworkflows
  namespace: workflows
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - clusterworkflowtemplates
  - cronworkflows
  verbs:
  - list
  - watch
  - get
  - patch
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - get
  - watch
  - update

