apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgA0oYGAqiFcv9NNANcLldPlDr7HsjMIPzUjJnjM8rarkXxcibkgfOpxuzSvKn/Q7eXYTI6KaaL5xC/ovu/du+3TuNtoS1zPsnQMuoGWHti5MiLrCrLWbc2d8p3NCDAopMprGQ2AR7uvgf7cJyPG4620nIFmAoovr6sUJ4jtxqPv4x7x6tohLJFCqDnTBvvCLuXJbvI3ijfD1oX/ev6nI3UC/oUNOV5kfXgOKf/l+HeWQniuHOKd9ROO9E2xPAYAyytbEWtkuWzlSxLrvojRISAOxuX0yHIFs+sGLQmPeF81MGxDHiQlBLo1GckPXJHyj5PDyRg2I0JMpt//SWrcIbW61gVvmuXChamYFuaMR0GtmtCffEPkLm2UQB2L/P83zpDJTFIxNvxLByCZQ5kQJuMDCYZShi50k9yCJSA2pw4Hpdf2+qCBX+9Hy7TBkj3euakEcew0VGKEEn9DQA7zhK8D0Ke+LGrXaLtOAqHF8SGr6M4YYTGV8HgoH6SfuJx7TtncVGJMXjeZzlxfVU1XeV2ogAhadGb1NUI22RLaneHpxnbGDf8GOmOwFsd7jNsD4+XZ4NsI399gjSzfBNbctSbDpgSU22mYWO3rBStNNZ1eQAPh5IDJQJdj6UnVAYqsbuBkeT+4xImkktgWaRc85nkOLIk02PFtQ0rDbPzBvs6qzdjj40ry69Tl4ADh4T4aGPQZZJog7pTBMiBPQBOsdovbkIj18Mmp/wvJRKJ0mj6P7zgMp0qzJJzyXDwDmdDlIuT4f+Fzggpt2Osjrh+VfWiuf/vXHao6FGBjtNDG+k3Jrlw1pp+FqINmhtPP8AvomZuRwnoM2RwvTjheCvEioh3ZFHXFj7TFxbGcZ09TnLDrIyKDQmEr+du5NCVzDaJI8CEKHtcRv7mocx0C6GCKOTWbiqkXvEKJ7HCUmVgN47DruKFxs4XEa42o7FWTB+xnPxRBtp6JCdnwjcHF6gRzQWiLrwGGp7Wl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

