apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBkt8ODWITvwUaWPm6bfDffxUQXZ9oJu8SPCqQB8aZ61GyCUqKQ/AlO4g1a/HnKVaf2shHmyWWXDljrhdAAiUh6B0i0rPDFGv2JaVikYMW+z0lXeeH2YMYnX3Zr9mU/xtgkRRrfLrvx3rkil5pj9mHSeSU2ofC2GCPF0lgdNPBnjbm1ytnggLWdX2JLwXZQ5uDplLdnR8x+14n4+4EKk0xr5m3ruiBXDNZTfz7w65q7NNWhcFTx/AYMaqy9L3XrLz/NQqxps3V8tyvIYC8AydulLo6eTLm5+9npbFqndgrQVdC6yzVg3EKX+2prIR9xFLMuF+wyuQhw/oIiy9ktSwXg29KGlPkc31qu4n1HIi4Qm/ldx5lclQNkKPFJ5GeYb5b3SAA8nxAsbvRPpE+nMrGKQisN2s/VLPIg853epQ7rFvtGY4Be2WfmBRCRXybJh14Ad6tLkxhJTQm1ssWXnaifsNkfgD7bf9gKFZUMk1v813Iw/lWExdwJGGf7+dkUyeaNOTnMiP572S3DgA2s4f1vswupHdTsOsc1aQvMhNfEmH/YpJLgcFKXBJ4lHlh603I7957CHufh1UOTU5WNMksnf8uzvmQOUyHpo14Lr0bnby7UnYO6NS+7OtxfRTezmT5oMtNaXQW4ZRnA8OcOM+xwgcEXCT7XMb30DPQba2pgO+Igcb8HIbKDEIUdco0Cp3VKkHc/KXs13sLo8B8WlC8LS/Y6yTvhqRbW8NEoiMJPLBXMOywlAukJo6exDU9LEbORtAuAUzabnexf8uDyvlTqJy0OkqVO+Eup6XdS0fsd014fPgric/g+UUFebER0bcz4oa1FeM4O4CTOm7zvJWe50hn3p/eg2PzfaDQHm4rtlLmdjM+B2fPBHH2UV7Hb5IsFPlAIlOYhn7gnKoomBHtfGCtBMWC5BwBrUybogW0OuHKYUjJ1DNSxJnG5WythdxaTSt6bvzMvLvKjRRrWhwnaF/EgwHnt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

