apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCPZKPLrU0qNRQj3LCEXCFB7yMHdY+X5Ric60/bdQIQbm4tS/iR1Evb1Otk6ZNp43bkn2OvbErbqnb4sc4h+2ahHQ8P6Y9oYmlJmTHZVi70E70JkaxCuZz3r20+EgSZEfz97k1iyc4mHLD7gn1OgvnZADAVXlnvPEkz9M2JKrLGzfYIi2Idw2rLxRfVQ2GO8aYKAwUJ80vFP++cVRYgd7FJ2hx8BIASuZpWTtRSUZe/FRgmEWP8ztX9EJSUrRKs2r6GroxxbWX+igsckkhtQLmQ2l9b0mptFc5c0/pHtbwMQjzolTMCySV7DPni+e7fpyxstoKGsJCNudd9f1XJY2WVADw/Lkry8cmr/fiNeDxzcDqWZX/mp6/eUcy8sNfu1PnY4lJXh2VMDztyTRSwuJ+hjJf2HkcpV7khKHIlx051mCfBhD8LN+UhFrsxTl0qGjgCJ5FuIqOlVRyNEsUFItLHyEKdiod5Ce3LKlxzZH8B7CZbcf7K8v5EG3Jy7G35Ru3NRn6zUNr0jPKfmVFPtLNjbkObTWe8YfbhcstC7phacVexXuyghdvJyY4Qa0apIXwxGuOffRQvzjkFsKaG0mSJtmpK7tXFUmr7X4DKMwyU9Bk13ub3+qA/KeSjcfxjmkeoglLiwIsNBApyUL2GWbiMKLVYnkeGiatRTYCKTgJjS/nbGOP9q4alJ0fcJy+unk1PjLPU7msJyvjLRN2NS3VymqqIswsLdpY2Zu+mCAqLsNbWgzifa46lTD5t72R1RZRSiHX2pntEo1SfglShRZDtfyn/4ShaAHq2ne5QlazLvcUV0O9ImuN8FadtOlbIhAvpzu0CRR1KKzVQoZxtzHJLjV/krP5s9bcorqEqAHAy0xE9t2750iujiC6MzgFffzK8Bp/xeZ+HXK5icXM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

